### ISSUE TITLE
Server crash after server restarts

### ISSUE THREAD

**Issue by 132ikl** [LionZXY/FastLogBlock#3]
Occasionally after leaving a modded server with the blocklog installed, the server will crash-loop on startup until the blocklog folder is reset. Looks like the block log is possibly being corrupted in some way after a server restart. This has happened multiple times. Technically this is happening on my fork at [132ikl/FastLogBlockServer](https://github.com/132ikl/FastLogBlockServer) but I don't see a reason a change such as that would make this happen.

Log: https://paste.ubuntu.com/p/f4vsTywS5s/

**Comment by LionZXY** [comment]
Big thanks for your issue. I will fix it today/tomorrow.

**Comment by 132ikl** [comment]
Any update?

**Comment by LionZXY** [comment]
Nope. I am a liar

**Comment by 132ikl** [comment]
:(

**Comment by ghost** [comment]
pls fix mr dev

**Comment by LionZXY** [comment]
Actual yet?

**Comment by 132ikl** [comment]
Sorry, what?
